version: '2'
services:
  ldap:
    image: osixia/openldap:1.5.0
    environment:
      LDAP_DOMAIN: "ttk.kz"
    env_file:
     - ./inf.env
    volumes:
      - ./ldap/data/slapd/database:/var/lib/ldap
      - ./ldap/data/slapd/config:/etc/ldap/slapd.d
  ldap_admin:
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
    ports:
      - "6443:443"
    depends_on:
      - ldap
  gitlab:
    image: gitlab/gitlab-ce:latest
    volumes:
      - ./gitlab/gitlab_home/config:/etc/gitlab
      - ./gitlab/gitlab_home/logs:/var/log/gitlab
      - ./gitlab/gitlab_home/data:/var/opt/gitlab
    ports:
      - "8080:80"
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    restart: always
    environment:
      - MONGO_URL=mongodb://mongodb:27017/rocketchat?replicaSet=rs0
      - MONGO_OPLOG_URL=mongodb://mongodb:27017/local&replicaSet=rs0
      - ROOT_URL=http://localhost:3000
      - PORT=3000
      - DEPLOY_METHOD=docker
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    restart: always
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_ADVERTISED_HOSTNAME=mongodb
      - MONGODB_ENABLE_JOURNAL=true
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  mongodb_data: { driver: local }

